# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2hNW1IrepOq61gFUGreyEtIGV96fUcD
"""

import numpy as np

def ES(losses, confidence=None, VaR=None, use_PnL=False, alpha=None):
    if confidence is None and alpha is not None:
        confidence = alpha
    if VaR is None:
        VaR = np.percentile(losses, 100 * confidence)
    es_value = np.mean(losses[losses > VaR])
    return es_value

def es(losses, confidence=None, VaR=None, use_PnL=False, alpha=None):
    return ES(losses, confidence=confidence, VaR=VaR, use_PnL=use_PnL, alpha=alpha)

