# -*- coding: utf-8 -*-
"""qES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zu_TqLAO3bdPOCaWQgmP1XXbFFYlTIlj
"""

import numpy as np


def ES(losses, confidence=None, VaR=None, use_PnL=False):
    if VaR is None:
        VaR = np.percentile(losses, 100 * confidence)
    es_value = np.mean(losses[losses > VaR])
    return es_value

def es(losses, confidence=None, VaR=None, use_PnL=False):
    return ES(losses, confidence=confidence, VaR=VaR, use_PnL=use_PnL)