# -*- coding: utf-8 -*-
"""WhoAmI_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbwtU0EDVUZu63HDuLLTy4BqiW53lUl_
"""

def WhoAmI():
  return "qh2298"