# -*- coding: utf-8 -*-
"""qGetReturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBqrOwctlc4kuMJ0-fjNpj-GS4mTLjxk
"""

import yfinance as yf
import pandas as pd

def YahooData2returns(YahooData):

    adj_close_series = YahooData['Adj Close'].sort_index(ascending=True)

    price_list = adj_close_series.tolist()

    if len(price_list) < 2:
        return []

    returns = []
    for i in range(1, len(price_list)):
        lagged_return = price_list[i] / price_list[i - 1] - 1
        returns.append(lagged_return)
    return returns

def get_stock_data(symbol):
    data = yf.download(symbol)
    close_series = data['Close'].sort_index(ascending=True)
    return close_series