# -*- coding: utf-8 -*-
"""qGetReturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBqrOwctlc4kuMJ0-fjNpj-GS4mTLjxk
"""

import yfinance as yf
import pandas as pd
import numpy as np

def YahooData2returns(YahooData):
    prices = YahooData['Adj Close'].values
    returns = np.diff(prices) / prices[:-1]
    return returns

def get_stock_data(symbol):
    data = yf.download(symbol)
    prices = data['Adj Close']
    return prices