# -*- coding: utf-8 -*-
"""qGetReturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBqrOwctlc4kuMJ0-fjNpj-GS4mTLjxk
"""

import yfinance as yf
import numpy as np

def get_stock_data(symbol):
    data = yf.download(symbol)
    adj_close_prices = data['Close']
    price_array = adj_close_prices.values
    return price_array

def compute_lagged_returns(price_array):

    if len(price_array) < 2:
        return np.array([])
    lagged_returns = price_array[1:] / price_array[:-1] - 1

    return lagged_returns

symbol = "AAPL"
prices = get_stock_data(symbol)
returns = compute_lagged_returns(prices)

print("First 5 adjusted close prices:", prices[:5])
print("First 5 lagged returns:", returns[:5])